### ISSUE TITLE
[Quarto] [Excel export] Timestamp support

### ISSUE THREAD

**Issue by sebez** [KleeGroup/vertigo-extensions#12]
## Current behaviour

Currently, the Excel export in `Quarto` only supports Date fields with a hard-coded date-only format.

If my Date field is a timestamp, the time part is not displayed in the resulting Excel sheet. => KO
**Notice** : The value in the Excel sheet is a valid full timestamp. The issue is only on the displaying of the value.

Diving in the API, it seems the new Java 8 types `LocalDate` and `ZonedDateTime` and are not supported.

https://github.com/KleeGroup/vertigo-extensions/blob/c07d60af0cc8d692132d896d540f9074f1c54fe2/vertigo-quarto/src/main/java/io/vertigo/quarto/plugins/export/xls/XLSExporter.java#L196

```java
// Date
final HSSFCellStyle oddDateCellStyle = createRowCellStyle(workbook, true);
final HSSFCellStyle evenDateCellStyle = createRowCellStyle(workbook, true);
oddDateCellStyle.setDataFormat(HSSFDataFormat.getBuiltinFormat("m/d/yy" /* "m/d/yy h:mm" */));
evenDateCellStyle.setDataFormat(HSSFDataFormat.getBuiltinFormat("m/d/yy" /* "m/d/yy h:mm" */));
oddHssfStyleCache.put(DataType.Date, oddDateCellStyle);
evenHssfStyleCache.put(DataType.Date, evenDateCellStyle);
```

## Expected behaviour

It should be possible to export Timestamp fields in the Excel export.

**Comment by NPi2Loup** [comment]
Fix not complete
